---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Casper node

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
    - 
      Label: 
        default: Instance Configuration
      Parameters: 
      - InstanceType
      - EbsVolumeSize
      - KeyName
      - IpWhitelist
    - 
      Label: 
        default: Node Configuration
      Parameters: 
      - NetworkName
      - NetwoekIp
      - CustomInitScript
    - 
      Label: 
        default: Metadata
      Parameters: 
      - OwnerName
      - ProjectName
      - Environment
    ParameterLabels:
      KeyName: 
        default: KeyName (Optional)
      IpWhitelist:
        default: IpWhitelist (Required if SSH access is enabled)
      CustomInitScript: 
        default: CustomInitScript (Optional)

Parameters:

  InstanceType:
    Type: String
    Default: r5.large
    Description: Instance type for the nodes

  EbsVolumeSize:
    Type: Number
    Default: 250
    Description: Size of the EBS volume of the instances in GB

  KeyName:
    Type: String
    Default: ''
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Leave blank to disable SSH access.

  IpWhitelist:
    Type: String
    Default: ''
    Description: IP to allow SSH access to the node. (e.g. 1.2.3.4/32)

  #  ############## Service #############

  NetworkName:
    Type: String
    Default: delta-11
    Description: Name of the network

  NetworkIp:
    Type: String
    Default: '167.86.108.79'
    Description: IP of the network

  CustomInitScript:
    Type: String
    Default: |
      #!/bin/bash \n
      echo Custom Init Script
    Description: A custom script to execute before the node initialization. (Represent new lines with \n character)

  #  ############### Tags ###############

  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources

  ProjectName:
    Type: String
    Description: The name of the stack to which these resources belong

  Environment:
    Type: String
    Default: dev
    Description: Environment name to append to resources names and tags

Conditions:

  Never: !Equals [ true, false ]

Resources:

  NullResource:
    Type: Custom::NullResource
    Condition: Never

  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/network-2azs.yml
      Parameters:
        Identifier: !Sub casper-${Environment}
        VpcCidr: 172.16.0.0/16
        PublicSubnetsCidr: !Join [ ',', [ 172.16.0.0/20, 172.16.16.0/20 ] ]
        PrivateSubnetsCidr: !Join [ ',', [ 172.16.32.0/20, 172.16.48.0/20 ] ]
        SetNatGateway: false
        NatGatewayHA: false
        OwnerName: !Ref OwnerName
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  CasperNode:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/casper-node.yml
      Parameters:
        Identifier: !Sub casper-${Environment}
        VpcId: !GetAtt  Vpc.Outputs.VpcId
        SubnetIds: !GetAtt  Vpc.Outputs.PublicSubnetIds
        InstanceType: !Ref InstanceType
        EbsVolumeSize: !Ref EbsVolumeSize
        AmiId: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
        KeyName: !Ref KeyName
        IpWhitelist: !Ref IpWhitelist
        NetworkName: !Ref NetworkName
        NetworkIp: !Ref NetworkIp
        CustomInitScript: !Ref CustomInitScript
        OwnerName: !Ref OwnerName      
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

Outputs:

  DashboardUrl:
    Description: CloudWatch dashboard URL
    Value: !GetAtt CasperNode.Outputs.DashboardUrl