---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Casper node

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
    - 
      Label: 
        default: Node Configuration
      Parameters: 
      - InstanceType
      - EbsVolumeSize
      - KeyName
      - IpWhitelist
    - 
      Label: 
        default: Metadata
      Parameters: 
      - OwnerName
      - ProjectName
      - Environment
    ParameterLabels: 
      KeyName: 
        default: Name of an existing EC2 KeyPair to enable SSH access to the instances. Leave blank to disable SSH access.
      IpWhitelist:
        default: Which IP should be allowed for SSH access? (e.g. 1.2.3.4/32)

Parameters:

  InstanceType:
    Type: String
    Default: t3.medium
    Description: Instance type for the nodes
    AllowedValues: [ t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge, t3a.nano, t3a.micro, t3a.small, t3a.medium, t3a.large, t3a.xlarge, t3a.2xlarge, t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge, m5ad.large, m5ad.xlarge, m5ad.2xlarge, m5ad.4xlarge, m5ad.12xlarge, m5ad.24xlarge, m5a.large, m5a.xlarge, m5a.2xlarge, m5a.4xlarge, m5a.12xlarge, m5a.24xlarge, m5d.large, m5d.xlarge, m5d.2xlarge, m5d.4xlarge, m5d.12xlarge, m5d.24xlarge, m5d.metal, m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge, m5.12xlarge, m5.24xlarge, m5.metal, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge, m4.16xlarge, a1.medium, a1.large, a1.xlarge, a1.2xlarge, a1.4xlarge, c5n.large, c5n.xlarge, c5n.2xlarge, c5n.4xlarge, c5n.9xlarge, c5n.18xlarge, c5d.large, c5d.xlarge, c5d.2xlarge, c5d.4xlarge, c5d.9xlarge, c5d.18xlarge, c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge, c5.18xlarge, c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, f1.2xlarge, f1.4xlarge, f1.16xlarge, g2.2xlarge, g2.8xlarge, g3s.xlarge, g3.4xlarge, g3.8xlarge, g3.16xlarge, p2.xlarge, p2.8xlarge, p2.16xlarge, p3.2xlarge, p3.8xlarge, p3.16xlarge, p3dn.24xlarge, r5ad.large, r5ad.xlarge, r5ad.2xlarge, r5ad.4xlarge, r5ad.12xlarge, r5ad.24xlarge, r5a.large, r5a.xlarge, r5a.2xlarge, r5a.4xlarge, r5a.12xlarge, r5a.24xlarge, r5d.large, r5d.xlarge, r5d.2xlarge, r5d.4xlarge, r5d.12xlarge, r5d.24xlarge, r5d.metal, r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r5.12xlarge, r5.24xlarge, r5.metal, r4.large, r4.xlarge, r4.2xlarge, r4.4xlarge, r4.8xlarge, r4.16xlarge, x1.16xlarge, x1e.xlarge, x1e.2xlarge, x1e.4xlarge, x1e.8xlarge, x1e.16xlarge, x1e.32xlarge, x1.32xlarge, z1d.large, z1d.xlarge, z1d.2xlarge, z1d.3xlarge, z1d.6xlarge, z1d.12xlarge, z1d.metal, d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge, h1.2xlarge, h1.4xlarge, h1.8xlarge, h1.16xlarge, i3.large, i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge, i3.16xlarge, i3.metal, i3en.large, i3en.xlarge, i3en.2xlarge, i3en.3xlarge, i3en.6xlarge, i3en.12xlarge, i3en.24xlarge ]

  EbsVolumeSize:
    Type: Number
    Default: 40
    Description: Size of the EBS volume of the instances in GB

  KeyName:
    Type: String
    Default: ''
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances.

  IpWhitelist:
    Type: String
    Default: ''
    Description: IP to allow SSH access to the node. Used only if you enable SSH access by selecting a Key Pair.

  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources

  ProjectName:
    Type: String
    Description: The name of the stack to which these resources belong

  Environment:
    Type: String
    Default: dev
    Description: Environment name to append to resources names and tags

Conditions:

  Never: !Equals [ true, false ]

Resources:

  NullResource:
    Type: Custom::NullResource
    Condition: Never

  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/network-2azs.yml
      Parameters:
        Identifier: !Sub casper-${Environment}
        VpcCidr: 172.16.0.0/16
        PublicSubnetsCidr: !Join [ ',', [ 172.16.0.0/20, 172.16.16.0/20 ] ]
        PrivateSubnetsCidr: !Join [ ',', [ 172.16.32.0/20, 172.16.48.0/20 ] ]
        SetNatGateway: false
        NatGatewayHA: false
        OwnerName: !Ref OwnerName
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  CasperNode:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./templates/casper-node.yml
      Parameters:
        Identifier: !Sub casper-${Environment}
        VpcId: !GetAtt  Vpc.Outputs.VpcId
        SubnetIds: !GetAtt  Vpc.Outputs.PublicSubnetIds
        InstanceType: !Ref InstanceType
        EbsVolumeSize: !Ref EbsVolumeSize
        AmiId: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
        KeyName: !Ref KeyName
        IpWhitelist: !Ref IpWhitelist
        OwnerName: !Ref OwnerName      
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

Outputs:

  DashboardUrl:
    Description: CloudWatch dashboard URL
    Value: !GetAtt CasperNode.Outputs.DashboardUrl