AWSTemplateFormatVersion: 2010-09-09
Description: Casper node
Transform:
- AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: casper-node
    Description: Casper Node Infrastructure
    Author: CasperLabs
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1k5khq956e42f/2054f94407856d9e82c9fc72cd32f65f
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-1k5khq956e42f/13c759f83e714715dbc607e521ad4b52
    Labels:
    - casper
    - blockchain
    HomePageUrl: https://github.com/nclouds/casper-infrastructure
    SemanticVersion: '0.0.1'
    SourceCodeUrl: https://github.com/nclouds/casper-infrastructure
Parameters:
  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources
  ProjectName:
    Type: String
    Description: The name of the stack to which these resources belong
  Environment:
    Type: String
    Default: dev
    Description: Environment name to append to resources names and tags
Conditions:
  Never:
    Fn::Equals:
    - true
    - false
Resources:
  NullResource:
    Type: Custom::NullResource
    Condition: Never
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-1k5khq956e42f/02821e353d10c3528421dfca722d9c16.template
      Parameters:
        Identifier:
          Fn::Sub: casper-${Environment}
        VpcCidr: 172.16.0.0/16
        PublicSubnetsCidr:
          Fn::Join:
          - ','
          - - 172.16.0.0/20
            - 172.16.16.0/20
        PrivateSubnetsCidr:
          Fn::Join:
          - ','
          - - 172.16.32.0/20
            - 172.16.48.0/20
        SetNatGateway: false
        NatGatewayHA: false
        OwnerName:
          Ref: OwnerName
        ProjectName:
          Ref: ProjectName
        Environment:
          Ref: Environment
  CasperNode:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-1k5khq956e42f/4feca88b690bbc6d282bb001fe96bcc6.template
      Parameters:
        Identifier:
          Fn::Sub: casper-${Environment}
        VpcId:
          Fn::GetAtt:
          - Vpc
          - Outputs.VpcId
        SubnetIds:
          Fn::GetAtt:
          - Vpc
          - Outputs.PublicSubnetIds
        InstanceType: t3.medium
        AmiId: /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
        KeyName: ronaldo
        OwnerName:
          Ref: OwnerName
        ProjectName:
          Ref: ProjectName
        Environment:
          Ref: Environment
